In [2]:
import numpy as np
import pandas as pd

In [3]:
# How to create a data frame

data = {
    'Name' : ['Ashraf','Nikhil','Dilip','Abhishek'],
    'Age' : [23,24,25,26],
    'City' : ['Punjab','Bihar','Goa','Delhi'],
    'Salary' : [25000,35222,25001,15666]
}
df1 = pd.DataFrame(data)

In [4]:
df1

       Name  Age    City  Salary
0    Ashraf   23  Punjab   25000
1    Nikhil   24   Bihar   35222
2     Dilip   25     Goa   25001
3  Abhishek   26   Delhi   15666

In [5]:
data_list = [
    ['John', 28, 'New York', 65000],
    ['Anna', 34, 'Paris', 70000],
    ['Peter', 29, 'Berlin', 62000],
    ['Linda', 42, 'London', 85000]
]
df2 = pd.DataFrame(data_list)

In [6]:
df2  # as you see here the columns name is also a indexing value if you need to add name do this

       0   1         2      3
0   John  28  New York  65000
1   Anna  34     Paris  70000
2  Peter  29    Berlin  62000
3  Linda  42    London  85000

In [7]:
col = ['Name','Age','City','Salary']
df2 = pd.DataFrame(data_list, columns = col)

In [8]:
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [9]:
# What is selection and indexing of columns

df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [10]:
# for selecting single column
df2['Name']

0     John
1     Anna
2    Peter
3    Linda
Name: Name, dtype: str

In [11]:
# for selecting multiple columns together
df2[['Name','City']]

    Name      City
0   John  New York
1   Anna     Paris
2  Peter    Berlin
3  Linda    London

In [12]:
# How to add a new column in the existing data frame
df2["Designation"] = ["Doctor","Al ML Engg.","Data scientist","Engineer"]

In [13]:
df2 # here you can see the designation is add in the data frame

    Name  Age      City  Salary     Designation
0   John   28  New York   65000          Doctor
1   Anna   34     Paris   70000     Al ML Engg.
2  Peter   29    Berlin   62000  Data scientist
3  Linda   42    London   85000        Engineer

In [14]:
# How to remove a column in the existing data frame
df2.drop("Designation", axis = 1)

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [15]:
df2  # here you can see the Designation aagin came

    Name  Age      City  Salary     Designation
0   John   28  New York   65000          Doctor
1   Anna   34     Paris   70000     Al ML Engg.
2  Peter   29    Berlin   62000  Data scientist
3  Linda   42    London   85000        Engineer

In [16]:
 # but above if we aagin print the df2 it will print the designation for removing it permanetly we use 
df2.drop("Designation", axis = 1, inplace = True)

In [17]:
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [18]:
df2 #  as you see here the Designation remove and not coming aagin

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [19]:
# How to acces the row 
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [20]:
df2.loc[0]

Name          John
Age             28
City      New York
Salary       65000
Name: 0, dtype: object

In [21]:
df2.loc[[0,1]]

   Name  Age      City  Salary
0  John   28  New York   65000
1  Anna   34     Paris   70000

In [22]:
# and by indexing we use 
df2.iloc[3]

Name       Linda
Age           42
City      London
Salary     85000
Name: 3, dtype: object

In [23]:
# Selecting subset of row and column
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [24]:
df2.loc[[0,1]] [["City", "Salary"]]

       City  Salary
0  New York   65000
1     Paris   70000

In [25]:
df2.loc[0]["Name"]

'John'

In [26]:
df2.loc[[2,3]][["Name", "Age"]]

    Name  Age
2  Peter   29
3  Linda   42

In [27]:
# for removing the row form the existing data frame
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [28]:
df2.drop(0, axis = 0)

    Name  Age    City  Salary
1   Anna   34   Paris   70000
2  Peter   29  Berlin   62000
3  Linda   42  London   85000

In [29]:
# Conditional Selection 
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [30]:
# i only want to see those people whose age is above 30
df2[df2["Age"] > 30]

    Name  Age    City  Salary
1   Anna   34   Paris   70000
3  Linda   42  London   85000

In [31]:
# i only want to see those people whose age is above 30 and must be belong to paris
df2[(df2["Age"] > 30) & (df2["City"] == "Paris")]

   Name  Age   City  Salary
1  Anna   34  Paris   70000