In [2]:
import numpy as np
import pandas as pd

**How to merege**

In [3]:
# DataFrame 1: Employees information
employees = pd.DataFrame({
    'employee_id': [1,2,3,4,5],
    'name': ['John', 'Anna', 'Peter', 'Linda', 'Bob'],
    'department': ['HR', 'IT', 'Finance', 'IT', 'HR']
})

# DataFrame 2: Salary information
salaries = pd.DataFrame({
    'employee_id': [1,2,3,6,7],
    'salary': [60000,80000,65000,70000,90000],
    'bonus': [5000, 10000, 7000, 8000, 12000]
})

In [4]:
employees

   employee_id   name department
0            1   John         HR
1            2   Anna         IT
2            3  Peter    Finance
3            4  Linda         IT
4            5    Bob         HR

In [5]:
salaries

   employee_id  salary  bonus
0            1   60000   5000
1            2   80000  10000
2            3   65000   7000
3            6   70000   8000
4            7   90000  12000

In [6]:
pd.merge(employees,salaries)  # here Pandas automatically uses how='inner' and identifies the common column employee_id in both DataFrames.

   employee_id   name department  salary  bonus
0            1   John         HR   60000   5000
1            2   Anna         IT   80000  10000
2            3  Peter    Finance   65000   7000

In [7]:
pd.merge(employees,salaries, on = 'employee_id')   # by using ---on--- we tell merge according to this

   employee_id   name department  salary  bonus
0            1   John         HR   60000   5000
1            2   Anna         IT   80000  10000
2            3  Peter    Finance   65000   7000

In [8]:
pd.merge(employees,salaries, on = 'employee_id', how = 'inner')   # how='inner' means keep only the rows that have matching values in both DataFrames

   employee_id   name department  salary  bonus
0            1   John         HR   60000   5000
1            2   Anna         IT   80000  10000
2            3  Peter    Finance   65000   7000

In [9]:
pd.merge(employees,salaries, on = 'employee_id', how = 'outer')   # how='outer' means keep all rows from both DataFrames, whether their IDs match or not

   employee_id   name department   salary    bonus
0            1   John         HR  60000.0   5000.0
1            2   Anna         IT  80000.0  10000.0
2            3  Peter    Finance  65000.0   7000.0
3            4  Linda         IT      NaN      NaN
4            5    Bob         HR      NaN      NaN
5            6    NaN        NaN  70000.0   8000.0
6            7    NaN        NaN  90000.0  12000.0

In [10]:
pd.merge(employees,salaries, on = 'employee_id', how = 'left')  # how='left' means keep all rows from the left DataFrame and add matching data from the right DataFrame
# employees is the left DataFrame, and salaries is the right DataFrame

   employee_id   name department   salary    bonus
0            1   John         HR  60000.0   5000.0
1            2   Anna         IT  80000.0  10000.0
2            3  Peter    Finance  65000.0   7000.0
3            4  Linda         IT      NaN      NaN
4            5    Bob         HR      NaN      NaN

In [11]:
pd.merge(employees,salaries, on = 'employee_id', how = 'right')  # how='right' means keep all rows from the right DataFrame and add matching data from the left DataFrame
# employees is the left DataFrame, and salaries is the right DataFrame

   employee_id   name department  salary  bonus
0            1   John         HR   60000   5000
1            2   Anna         IT   80000  10000
2            3  Peter    Finance   65000   7000
3            6    NaN        NaN   70000   8000
4            7    NaN        NaN   90000  12000

**Concatination of 2 Data frame**

In [12]:
df1 = pd.DataFrame({
    'A': ['A0', 'A1', 'A2'],
    'B': ['B0', 'B1', 'B2'],
    'C': ['C0', 'C1', 'C2']
})

df2 = pd.DataFrame({
    'A': ['A3', 'A4', 'A5'],
    'B': ['B3', 'B4', 'B5'],
    'C': ['C3', 'C4', 'C5']
})

In [13]:
df1

    A   B   C
0  A0  B0  C0
1  A1  B1  C1
2  A2  B2  C2

In [14]:
df2

    A   B   C
0  A3  B3  C3
1  A4  B4  C4
2  A5  B5  C5

In [15]:
pd.concat([df1,df2]) # this is concatinate base on the column

    A   B   C
0  A0  B0  C0
1  A1  B1  C1
2  A2  B2  C2
0  A3  B3  C3
1  A4  B4  C4
2  A5  B5  C5

In [16]:
pd.concat([df2,df1]) # this is concatinate base on the column

    A   B   C
0  A3  B3  C3
1  A4  B4  C4
2  A5  B5  C5
0  A0  B0  C0
1  A1  B1  C1
2  A2  B2  C2

In [17]:
pd.concat([df1,df2], axis = 1) # this is concatinate base on the row

    A   B   C   A   B   C
0  A0  B0  C0  A3  B3  C3
1  A1  B1  C1  A4  B4  C4
2  A2  B2  C2  A5  B5  C5

**Joining 2 Data Frames**

In [18]:
df1 = pd.DataFrame({
    'name': ['Alice', 'Bob', 'Charlie']
}, index=[1, 2, 3])

# Second DataFrame
df2 = pd.DataFrame({
    'score': [85, 90, 75]
}, index=[2, 3, 4])

In [19]:
df1

      name
1    Alice
2      Bob
3  Charlie

In [20]:
df2

   score
2     85
3     90
4     75

In [21]:
df1.join(df2)

      name  score
1    Alice    NaN
2      Bob   85.0
3  Charlie   90.0

In [22]:
df1.join(df2, how = 'outer')

      name  score
1    Alice    NaN
2      Bob   85.0
3  Charlie   90.0
4      NaN   75.0