In [49]:
import numpy as np
import pandas as pd

**Group By**

In [50]:
data = {
    'Category': ['A', 'B', 'A', 'B', 'A', 'B', 'A', 'B'],
    'Store': ['S1', 'S1', 'S2', 'S2', 'S1', 'S2', 'S2', 'S1'],
    'Sales': [100, 200, 150, 250, 120, 180, 200, 300],
    'Quantity': [10, 15, 12, 18, 8, 20, 15, 25],
    'Date': pd.date_range('2023-01-01', periods=8)
}
df = pd.DataFrame(data)

In [51]:
df

  Category Store  Sales  Quantity       Date
0        A    S1    100        10 2023-01-01
1        B    S1    200        15 2023-01-02
2        A    S2    150        12 2023-01-03
3        B    S2    250        18 2023-01-04
4        A    S1    120         8 2023-01-05
5        B    S2    180        20 2023-01-06
6        A    S2    200        15 2023-01-07
7        B    S1    300        25 2023-01-08

In [52]:
# Group by category and calculate the sum of sales
cat = df.groupby('Category')
for i, v in cat:
    print(i)
    print(v)              # see this very carefully not a part of this

A
  Category Store  Sales  Quantity       Date
0        A    S1    100        10 2023-01-01
2        A    S2    150        12 2023-01-03
4        A    S1    120         8 2023-01-05
6        A    S2    200        15 2023-01-07
B
  Category Store  Sales  Quantity       Date
1        B    S1    200        15 2023-01-02
3        B    S2    250        18 2023-01-04
5        B    S2    180        20 2023-01-06
7        B    S1    300        25 2023-01-08

In [53]:
# the main is here 
cat = df.groupby('Category')['Sales'].sum()
cat

Category
A    570
B    930
Name: Sales, dtype: int64

In [54]:
# Group by Stores and calculate the sum of sales
sal = df.groupby('Store')['Sales'].sum()
sal

Store
S1    720
S2    780
Name: Sales, dtype: int64

In [55]:
# Group by multiple columns
# Group by Category and store
mul = df.groupby(['Category','Store'])['Sales'].sum()
mul

Category  Store
A         S1       220
          S2       350
B         S1       500
          S2       430
Name: Sales, dtype: int64

**AGGREGATION**

In [56]:
df

  Category Store  Sales  Quantity       Date
0        A    S1    100        10 2023-01-01
1        B    S1    200        15 2023-01-02
2        A    S2    150        12 2023-01-03
3        B    S2    250        18 2023-01-04
4        A    S1    120         8 2023-01-05
5        B    S2    180        20 2023-01-06
6        A    S2    200        15 2023-01-07
7        B    S1    300        25 2023-01-08

In [57]:
# THESE ARE THE FEW EXAMPLE OF AGGREGATION
df['Sales'].mean()

np.float64(187.5)

In [58]:
df['Sales'].median()

np.float64(190.0)

In [59]:
df['Sales'].mode()

0    200
Name: Sales, dtype: int64

In [60]:
df['Sales'].min()

np.int64(100)

In [61]:
df['Sales'].max()

np.int64(300)

In [62]:
df['Sales'].count()

np.int64(8)

In [63]:
df['Sales'].std()

np.float64(66.06274074155351)

In [67]:
# and if we want to do multiple aggregation together then 
df['Sales'].agg(['max','mean','median', 'min', 'sum', 'count', 'std'])  # only mode did not work here

max        300.000000
mean       187.500000
median     190.000000
min        100.000000
sum       1500.000000
count        8.000000
std         66.062741
Name: Sales, dtype: float64